task:
  type: "improve-corrupted-generation"
  num_facts_to_consider:
    - 2
    - 4
    - 6
    - 8
    - 10
  generation_dir: "data/corrupted/"
  repetition_path: "data/tuned_generation/repetitive-mistral.jsonl"
  informative_path: "data/tuned_generation/info-mistral.jsonl"