task:
  type: "score-generation"
  scorer:
    type: "decompose"
    abstention_detector: "factscore"
    decomposer:
      type: "deduplicated"
      base_decomposer:
        type: "refined-decomposer"
        sentencize: False
        base_decomposer:
          type: "factscore"
          model_name: "mistralai/Mistral-7B-Instruct-v0.2"
          base_url: "http://localhost:9871/v1"
          api_key: "token-abc123"
          example_path: "factscore_decomp_examples.txt"
          sentencize: False
        decontextualizer:
          type: "default"
          model_name: "mistralai/Mistral-7B-Instruct-v0.2"
          example_path: "decontextualize_examples.txt"
          base_url: "http://localhost:9871/v1"
          api_key: "token-abc123"
        relevancy_scorer:
          type: "relevancy-scorer"
          generation_prompt_template: "tell me a bio of {topic}."
          model_name: "mistralai/Mistral-7B-Instruct-v0.2"
          example_path: "relevancy_examples.txt"
          base_url: "http://localhost:9871/v1"
          api_key: "token-abc123"
      sentence_level_checkworthy_scorer:
        type: "llm-checkworthy-general"
        model_name: "mistralai/Mistral-7B-Instruct-v0.2"
        base_url: "http://localhost:9871/v1"
        api_key: "token-abc123"
        in_batch_num: 4
      claim_level_checkworthy_scorer:
        type: "unli-confidence-boost"
        bleached_templates:
          - "{topic} is a person."
          - "{topic} breathes."
          - "{topic} exists."
          - "{topic} is a name."
          - "{topic} is unique."
          - "{topic} is famous."
          - "{topic} has some abilities."
          - "somebody knows {topic}."
          - "{topic} is a star."
        entailer:
          type: "soft-entailer"
          model_name: "Zhengping/roberta-large-unli"
          max_length: 256
          internal_batch_size: 32
        cap_entailer:
          type: "default"
          model_name: "MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli"
          max_length: 256
          internal_batch_size: 512
      entailer:
        type: "default"
        # model_name: "ynie/roberta-large-snli_mnli_fever_anli_R1_R2_R3-nli"
        model_name: "MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli"
        # model_name: "MoritzLaurer/DeBERTa-v3-large-mnli-fever-anli-ling-wanli"
        max_length: 256
        internal_batch_size: 512
    base_scorer:
      type: "safe-support"
      model_name: "mistralai/Mistral-7B-Instruct-v0.2"
      retriever:
        type: "serper"
        model_name: "mistralai/Mistral-7B-Instruct-v0.2"
        serper_api_key: ${SERPER_API_KEY}
        base_url: "http://localhost:9871/v1"
        api_key: "token-abc123"
        cache_path: ".cache/serper/serper_cache.db"
        top_k: 3
      base_url: "http://localhost:9871/v1"
      api_key: "token-abc123"
    aggregator:
      type: "factscore"
      gamma: 10
  input_path: ${OUTPUT_PATH}
  output_path: ${SCORE_PATH}