task:
  type: "score-generation"
  scorer:
    type: "decompose"
    abstention_detector: "factscore"
    decomposer:
      type: "factscore"
      model_name: "gpt-3.5-turbo"
      example_path: "factscore_decomp_examples.txt"
    base_scorer:
      type: "llm-support"
      db_path: "db/enwiki-20230401.db"
      cache_dir: ".cache/"
      model_name: "gpt-3.5-turbo"
    aggregator:
      type: "factscore"
      gamma: 10
  input_path: ${OUTPUT_PATH}
  output_path: ${SCORE_PATH}