task:
  type: "score-generation"
  scorer:
    type: "decompose"
    abstention_detector: "factscore"
    decomposer:
      type: "factscore"
      model_name: "mistralai/Mistral-7B-Instruct-v0.2"
      base_url: "http://localhost:9871/v1"
      api_key: "token-abc123"
      example_path: "data/factscore_decomp_examples.txt"
    base_scorer:
      type: "llm-support"
      db_path: "db/enwiki-20230401.db"
      cache_dir: ".cache/"
      model_name: "mistralai/Mistral-7B-Instruct-v0.2"
      base_url: "http://localhost:9871/v1"
      api_key: "token-abc123"
    aggregator:
      type: "factscore"
      gamma: 10
  input_path: ${OUTPUT_PATH}
  output_path: ${SCORE_PATH}