task:
  type: "generation"
  topic_path: "data/entity_filtering/sampled_test.txt"
  model_name: "mistralai/Mistral-7B-Instruct-v0.2"
  base_url: "http://localhost:9871/v1"
  api_key: "token-abc123"
  output_path: ${OUTPUT_PATH}
  prompt: ${PROMPT}