task:
  type: "corrupt-generation"
  fact_checker:
    type: "llm-support"
    model_name: "mistralai/Mistral-7B-Instruct-v0.2"
    retriever:
      type: "wikidoc"
      db_path: "db/enwiki-20230401.db"
      cache_path: ".cache/retriever-cache.json"
      embed_cache_path: ".cache/retriever-embed-cache.pkl"
      retrieval_type: "gtr-t5-large"
      batch_size: 256
      device: "cuda:0"
    base_url: "http://localhost:9871/v1"
    api_key: "token-abc123"
  generation_path: "data/scores/tuned_generation/null-mistral-factscore.json"
  corruption_ratio: 0.5
  cache_path_overwrite: ".cache/.gpt-3.5-turbo-cache.db"
  merge_cache_path_overwrite: ".cache/.gpt-4o-cache.db"
  output_dir: "data/corrupted/"