task:
  type: "create-training-examples"
  model_name: "mistralai/Mistral-7B-Instruct-v0.2"
  base_url: "http://localhost:9871/v1"
  api_key: "token-abc123"
  instruction_prompts:
    - "Tell me a short paragraph of obviously true scientific facts. You will be provided with a person name, ignore it and only generate a paragraph of random scientific facts."
    - "Sure. Please provide a name to start."
  input_example_prompt: "Name: {topic}"
  output_example_prompt: "{generation}"
  num_samples_per_topic: 5
  example_path: "data/in-context-examples/relevancy.txt"
  input_path: ${INPUT_PATH}
  output_path: ${OUTPUT_PATH}